<?php
// AvianVisitors - local species summary endpoint.
//
// The detail modal calls /avian/api/wiki.php?sci=<name> for the species
// description. Runtime requests are served from the bundled local JSON
// store generated by avian/scripts/fetch_wiki_descriptions.py, so the Pi
// does not need to reach Wikipedia while someone is browsing.

declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: public, max-age=86400');

$sci = trim((string)($_GET['sci'] ?? ''));
if ($sci === '') {
    http_response_code(400);
    echo json_encode(['error' => 'sci required']);
    exit;
}
if (!preg_match('/^[A-Za-z]{2,40}(?:[ ][a-z]{2,40}){1,3}$/', $sci)) {
    http_response_code(400);
    echo json_encode(['error' => 'invalid sci']);
    exit;
}

function normalized_lang(): string {
    $raw = (string)($_GET['lang'] ?? $_GET['locale'] ?? '');
    $raw = str_replace('_', '-', strtolower(trim($raw)));
    if ($raw === 'zh' || $raw === 'zh-cn' || strpos($raw, 'zh-hans') === 0 || $raw === 'zh-sg') {
        return 'zh-CN';
    }
    return 'en';
}

$storePath = dirname(__DIR__) . '/assets/data/species-descriptions.json';
$raw = is_file($storePath) ? file_get_contents($storePath) : false;
if ($raw === false) {
    echo json_encode(['extract' => null, 'thumbnail' => null, 'local' => true]);
    exit;
}

$store = json_decode($raw, true);
if (!is_array($store) || !isset($store['species']) || !is_array($store['species'])) {
    echo json_encode(['extract' => null, 'thumbnail' => null, 'local' => true]);
    exit;
}

$j = $store['species'][$sci] ?? null;
if (!is_array($j)) $j = [];
$lang = normalized_lang();
$localized = $lang !== 'en' && isset($j['i18n'][$lang]) && is_array($j['i18n'][$lang])
    ? $j['i18n'][$lang]
    : $j;

echo json_encode([
    'extract'   => $localized['extract'] ?? null,
    'thumbnail' => $j['thumbnail'] ?? null,
    'title'     => $localized['title'] ?? ($j['title'] ?? null),
    'source'    => $j['source'] ?? null,
    'lang'      => $lang,
    'local'     => true,
]);
